component:
  - 'custom_components/**/*'

documentation:
  - 'README.md'
  - 'examples/**/*'

test:
  - 'tests/**/*'
  - 'pytest.ini'
  - 'requirements-test.txt'

infrastructure:
  - '.github/**/*'
  - 'hacs.json' 