name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
sort-direction: ascending

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'infrastructure'
      - 'automation'
      - 'documentation'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'documentation'
      - 'dependencies'
  default: patch

template: |
  ## Changes

  $CHANGES

  ## How to Install
  
  ### HACS (Recommended)
  This integration is available in HACS. To install:
  1. Go to HACS > Integrations
  2. Add this repository as a custom repository
  3. Search for "AWS" and install
  4. Restart Home Assistant
  
  ### Manual
  1. Download the ZIP from this release
  2. Extract to your Home Assistant's `custom_components` directory
  3. Restart Home Assistant 