name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    env:
      VERSION_PREFIX: 0.1
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      
      - name: Run tests
        run: |
          pytest
      
      - name: Create ZIP package
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir -p release/custom_components
          cp -r custom_components/aws release/custom_components/
          cd release
          zip -r ../aws.zip .
      
      - name: Create prerelease
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Generate version based on date and run number
          VERSION="${VERSION_PREFIX}.$(date +'%Y%m%d').${{ github.run_number }}"
          echo "Using version: $VERSION"
          
          # Create new release with both a version tag and the "latest" label
          gh release create "v$VERSION" \
            --title "Development Build v$VERSION" \
            --notes "Automated development build from main branch" \
            --prerelease \
            --latest \
            aws.zip LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 