name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      
      - name: Run tests
        run: pytest
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Update version in manifest.json
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.get_version.outputs.VERSION }}"/' custom_components/aws/manifest.json
      
      - name: Create ZIP for release
        run: |
          mkdir -p release/custom_components
          cp -r custom_components/aws release/custom_components/
          cd release
          zip -r ../aws.zip .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: aws.zip 